### ISSUE TITLE
Download tracking fails with strange chars in the URL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/indico-plugins#14]
```
Task indico_piwik.queries.tracking.track_download_request with id 177f854b-c41e-402e-b3e7-f7504799b316 raised exception:
"KeyError(u'\\xb4',)"


Task was called with
args: (u"https://indico.cern.ch/event/242207/material/slides/0.pptx?\xb4'0x27",
       'Download - Lopienski-2013.07-students-2-secure-web-applications_print.pptx')
kwargs: {u'__current_plugin__': 'piwik'}.

The contents of the full traceback was:

Traceback (most recent call last):
  File "/opt/indico/env/lib/python2.7/site-packages/celery-3.1.18-py2.7.egg/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/indico/env/lib/python2.7/site-packages/indico-1.9.3-py2.7.egg/indico/core/celery/core.py", line 144, in __call__
    return super(IndicoTask, s).__call__(*args, **kwargs)
  File "/opt/indico/env/lib/python2.7/site-packages/celery-3.1.18-py2.7.egg/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/indico/env/lib/python2.7/site-packages/indico_piwik/queries/tracking.py", line 40, in track_download_request
    action_url = quote(download_url)
  File "/opt/rh/python27/root/usr/lib64/python2.7/urllib.py", line 1282, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xb4'
```

**Comment by ThiefMaster** [comment]
@OmeGak maybe you can check this out? Maybe we can simply strip the query string since it's not really relevant for tracking material downloads... At least unless someone adds something to the query string with the sole purpose of knowing in his Piwik statistics where a request came from...
